version: '2'

services:
    head:
        build: .
        ports: 
            - "22"
        volumes:
            - ~:/home/user/remote
            - /mnt/nfs/kaggle/cervix/data:/home/user/cervix-classif/data
